# ==============================================================================
# ED1 Full Features - Modular ESPHome Configuration
# ==============================================================================
#
# All-in-one configuration with all available ED1 features:
# - 1.44" TFT Display (ST7735) - Status display
# - 32x8 LED Matrix (WS2812B) - 256 RGB LEDs
# - 6 Capacitive Touch Buttons - Binary sensors
# - Light Sensor - Ambient light percentage
# - Buzzer - Audio output via PWM
# - IR Receiver - 38kHz infrared remote control
# - Bluetooth Proxy - Extends Home Assistant BLE range
# - WiFi/CPU/Uptime Sensors
#
# Usage:
#   1. Copy this file and rename (e.g., ed1-living-room.yaml)
#   2. Change the substitutions below
#   3. Run: esphome run <your-config>.yaml
#
# ==============================================================================

substitutions:
  device_name: ed1-full
  friendly_name: ED1 Full Features
  ap_ssid: ED1-Full-Rescue

packages:
  core: !include packages/core.yaml
  hardware: !include packages/hardware.yaml
  display: !include packages/display.yaml
  fonts: !include packages/fonts.yaml
  buzzer: !include packages/buzzer.yaml
  buttons: !include packages/buttons.yaml
  sensors: !include packages/sensors.yaml
  bluetooth: !include packages/bluetooth.yaml
  ir_receiver: !include packages/ir-receiver.yaml
  led_matrix: !include packages/led-matrix.yaml

# TFT display layout showing matrix text status
display:
  - id: !extend internal_display
    lambda: |-
      auto BLACK = Color(0, 0, 0);
      auto WHITE = Color(255, 255, 255);
      auto GREEN = Color(0, 255, 0);
      auto YELLOW = Color(255, 255, 0);
      auto GRAY = Color(100, 100, 100);

      it.fill(BLACK);
      it.print(64, 5, id(large_font), GREEN, TextAlign::TOP_CENTER, "ED1 FULL");
      it.print(64, 30, id(pixel_font), WHITE, TextAlign::TOP_CENTER, id(wifi_ip).state.c_str());
      it.printf(64, 50, id(pixel_font), WHITE, TextAlign::TOP_CENTER, "T:%.1f C", id(cpu_temp).state);

      if (id(matrix_text_input).state != "") {
        it.print(64, 75, id(large_font), YELLOW, TextAlign::TOP_CENTER, id(matrix_text_input).state.c_str());
      } else {
        it.print(64, 75, id(pixel_font), GRAY, TextAlign::TOP_CENTER, "Matrix Ready");
      }
