# ==============================================================================
# ED1 Status Display - Modular ESPHome Configuration
# ==============================================================================
#
# A status display showing WiFi, sensors, and system info.
#
# Usage:
#   1. Copy this file and rename (e.g., ed1-kitchen.yaml)
#   2. Change the substitutions below
#   3. Run: esphome run <your-config>.yaml
#
# ==============================================================================

substitutions:
  device_name: ed1-status
  friendly_name: ED1 Status Display
  ap_ssid: ED1-Status-Rescue

packages:
  core: !include packages/core.yaml
  hardware: !include packages/hardware.yaml
  display: !include packages/display.yaml
  fonts: !include packages/fonts.yaml
  buzzer: !include packages/buzzer.yaml
  buttons: !include packages/buttons.yaml
  sensors: !include packages/sensors.yaml
  bluetooth: !include packages/bluetooth.yaml

# Startup animation
esphome:
  on_boot:
    priority: -100
    then:
      - rtttl.play: 'startup:d=16,o=5,b=180:c,e,g,c6'
      - delay: 3s
      - lambda: 'id(boot_complete) = true;'

globals:
  - id: boot_complete
    type: bool
    initial_value: 'false'

# Status display layout
display:
  - id: !extend internal_display
    lambda: |-
      // Colors
      auto BLACK = Color(0, 0, 0);
      auto WHITE = Color(255, 255, 255);
      auto GREEN = Color(0, 255, 0);
      auto CYAN = Color(0, 255, 255);
      auto YELLOW = Color(255, 255, 0);
      auto ORANGE = Color(255, 165, 0);
      auto RED = Color(255, 0, 0);

      it.fill(BLACK);

      // Boot splash screen
      if (!id(boot_complete)) {
        it.print(64, 40, id(large_font), GREEN, TextAlign::CENTER, "ED1");
        it.print(64, 70, id(pixel_font), WHITE, TextAlign::CENTER, "Booting...");
        return;
      }

      // Header row: ED1 centered
      it.print(64, 4, id(large_font), GREEN, TextAlign::TOP_CENTER, "ED1");

      // WiFi icon on left (20px), centered between SSID and IP rows
      bool has_ip = !id(wifi_ip).state.empty();
      if (has_ip) {
        it.print(4, 26, id(icons_20), GREEN, "\U0000e63e");
      } else {
        // Blink yellow every other second
        int sec = (int)id(uptime_sensor).state;
        if (sec % 2 == 0) {
          it.print(4, 26, id(icons_20), YELLOW, "\U0000e63e");
        }
      }

      // SSID and IP to the right of WiFi icon (with spacing)
      it.print(28, 28, id(pixel_font), CYAN, id(wifi_ssid).state.c_str());
      it.print(28, 40, id(pixel_font), WHITE, id(wifi_ip).state.c_str());

      // Signal bars on right of header
      int rssi = (int)id(wifi_signal_sensor).state;
      int bars = 0;
      Color bar_color = RED;
      if (rssi > -50) { bars = 4; bar_color = GREEN; }
      else if (rssi > -60) { bars = 3; bar_color = GREEN; }
      else if (rssi > -70) { bars = 2; bar_color = YELLOW; }
      else if (rssi > -80) { bars = 1; bar_color = ORANGE; }

      for (int i = 0; i < 4; i++) {
        int bar_height = (i + 1) * 3;
        int bar_x = 110 + (i * 5);
        int bar_y = 18 - bar_height;
        if (i < bars) {
          it.filled_rectangle(bar_x, bar_y, 3, bar_height, bar_color);
        } else {
          it.rectangle(bar_x, bar_y, 3, bar_height, bar_color);
        }
      }

      // Light sensor (y=58)
      it.print(4, 58, id(icons_16), YELLOW, "\U0000e518");
      it.printf(22, 62, id(pixel_font), WHITE, "%.0f%%", id(light_sensor).state);

      // Temperature (y=78)
      it.print(4, 78, id(icons_16), ORANGE, "\U0000e1ff");
      it.printf(22, 82, id(pixel_font), WHITE, "%.0f C", id(cpu_temp).state);

      // Uptime (y=98)
      it.print(4, 98, id(icons_16), WHITE, "\U0000e8b5");
      int seconds = (int)id(uptime_sensor).state;
      int days = seconds / 86400;
      int hours = (seconds % 86400) / 3600;
      int mins = (seconds % 3600) / 60;
      if (days > 0) {
        it.printf(22, 102, id(pixel_font), WHITE, "%dd %dh %dm", days, hours, mins);
      } else if (hours > 0) {
        it.printf(22, 102, id(pixel_font), WHITE, "%dh %dm", hours, mins);
      } else {
        it.printf(22, 102, id(pixel_font), WHITE, "%dm %ds", mins, seconds % 60);
      }
