# ==============================================================================
# ED1 Citilab Board - Full Features Configuration (Sample)
# ==============================================================================
#
# Project: All-in-one configuration with all available ED1 features
# Board: ED1 Rev 2.3 (Citilab Edutec)
# Purpose: Home Assistant integration exposing all board capabilities
#
# This sample enables ALL available features on the ED1 board:
#   - 1.44" TFT Display (ST7735) - Status display
#   - 32x8 LED Matrix (WS2812B) - 256 RGB LEDs
#   - 6 Capacitive Touch Buttons - Binary sensors
#   - Light Sensor - Ambient light percentage
#   - Buzzer - Audio output via PWM
#   - Bluetooth Proxy - Extends Home Assistant BLE range
#   - WiFi/CPU/Uptime Sensors
#
# Usage:
#   1. Copy this file to your ESPHome config directory
#   2. Rename it (e.g., ed1-living-room.yaml)
#   3. Change the 'name' and 'friendly_name' fields below
#   4. Copy secrets.sample.yaml to secrets.yaml and fill in your credentials
#   5. Flash via ESPHome dashboard or CLI: esphome run <your-config>.yaml
#
# Documentation: https://github.com/glifocat/ed1-hoas
# License: Apache 2.0
#
# ==============================================================================

esphome:
  name: ed1-full
  friendly_name: ED1 Full Features

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  level: INFO

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "ED1-Rescue"
    password: !secret fallback_ap_password

captive_portal:

# ==============================================================================
# 1. HARDWARE BUSES (SPI + I2C)
# ==============================================================================
spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19

i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true
  id: bus_i2c

# ==============================================================================
# 2. FONTS
# ==============================================================================
font:
  - file: "fonts/pixelmix/pixelmix.ttf"
    id: pixel_font
    size: 8
  - file: "fonts/pixelmix/pixelmix.ttf"
    id: large_font
    size: 16

# ==============================================================================
# 3. DISPLAYS (TFT + LED MATRIX)
# ==============================================================================
display:
  # Internal TFT Display (ST7735 128x128)
  - platform: st7735
    id: internal_display
    cs_pin: GPIO5
    dc_pin: GPIO9
    reset_pin: GPIO10
    rotation: 0
    model: "INITR_GREENTAB"
    col_start: 2
    row_start: 1
    device_width: 128
    device_height: 128
    update_interval: 1s
    lambda: |-
      auto BLACK = Color(0, 0, 0);
      auto WHITE = Color(255, 255, 255);
      auto GREEN = Color(0, 255, 0);
      auto YELLOW = Color(255, 255, 0);
      auto GRAY = Color(100, 100, 100);

      it.fill(BLACK);
      it.print(64, 5, id(large_font), GREEN, TextAlign::TOP_CENTER, "ED1 FULL");
      it.print(64, 30, id(pixel_font), WHITE, TextAlign::TOP_CENTER, id(wifi_ip).state.c_str());
      it.printf(64, 50, id(pixel_font), WHITE, TextAlign::TOP_CENTER, "T:%.1f C", id(cpu_temp).state);

      if (id(matrix_text_input).state != "") {
        it.print(64, 75, id(large_font), YELLOW, TextAlign::TOP_CENTER, id(matrix_text_input).state.c_str());
      } else {
        it.print(64, 75, id(pixel_font), GRAY, TextAlign::TOP_CENTER, "Matrix Ready");
      }

  # LED Matrix Display (32x8 WS2812B)
  - platform: addressable_light
    id: led_matrix_display
    addressable_light_id: led_matrix_light
    width: 32
    height: 8
    pixel_mapper: |-
      if (x % 2 == 0) return (x * 8) + y;
      return (x * 8) + (7 - y);
    update_interval: 50ms
    lambda: |-
      auto v = id(led_matrix_light).current_values;
      auto c = Color(
        v.get_red() * 255.0f,
        v.get_green() * 255.0f,
        v.get_blue() * 255.0f
      );

      it.fill(Color(0, 0, 0));
      if (id(matrix_text_input).state != "") {
        it.print(0, 0, id(pixel_font), c, id(matrix_text_input).state.c_str());
      }

# ==============================================================================
# 4. LED MATRIX LIGHT (NEOPIXEL)
# ==============================================================================
light:
  - platform: neopixelbus
    type: GRB
    variant: WS2812X
    pin: GPIO12
    num_leds: 256
    name: "ED1 LED Matrix"
    id: led_matrix_light
    method: esp32_rmt
    default_transition_length: 0s
    color_correct: [40%, 40%, 40%]

# ==============================================================================
# 5. BUZZER (PWM OUTPUT)
# ==============================================================================
output:
  - platform: ledc
    pin: GPIO26
    id: buzzer_output

switch:
  - platform: output
    name: "ED1 Buzzer"
    id: buzzer_switch
    output: buzzer_output

# ==============================================================================
# 6. BLUETOOTH PROXY
# ==============================================================================
esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms

bluetooth_proxy:
  active: true

# ==============================================================================
# 7. TOUCH BUTTONS
# ==============================================================================
esp32_touch:
  setup_mode: false

binary_sensor:
  - platform: esp32_touch
    id: btn_up
    name: "ED1 Button Up"
    pin: GPIO4
    threshold: 500
    on_press:
      - logger.log: "Button Up PRESSED"

  - platform: esp32_touch
    id: btn_down
    name: "ED1 Button Down"
    pin: GPIO13
    threshold: 500
    on_press:
      - logger.log: "Button Down PRESSED"

  - platform: esp32_touch
    id: btn_left
    name: "ED1 Button Left"
    pin: GPIO2
    threshold: 500
    on_press:
      - logger.log: "Button Left PRESSED"

  - platform: esp32_touch
    id: btn_right
    name: "ED1 Button Right"
    pin: GPIO27
    threshold: 500
    on_press:
      - logger.log: "Button Right PRESSED"

  - platform: esp32_touch
    id: btn_ok
    name: "ED1 Button OK"
    pin: GPIO15
    threshold: 500
    on_press:
      - logger.log: "Button OK PRESSED"

  - platform: esp32_touch
    id: btn_x
    name: "ED1 Button X"
    pin: GPIO14
    threshold: 500
    on_press:
      - logger.log: "Button X PRESSED"

# ==============================================================================
# 8. SENSORS
# ==============================================================================
sensor:
  - platform: wifi_signal
    name: "ED1 WiFi Signal"
    update_interval: 60s

  - platform: uptime
    name: "ED1 Uptime"

  - platform: internal_temperature
    name: "ED1 CPU Temperature"
    id: cpu_temp

  - platform: adc
    pin: GPIO34
    name: "ED1 Light Level"
    id: light_sensor
    attenuation: 12db
    update_interval: 1s
    unit_of_measurement: "%"
    device_class: ""
    filters:
      - multiply: 30.3

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "ED1 IP Address"
      id: wifi_ip

# ==============================================================================
# 9. TEXT INPUT FOR LED MATRIX
# ==============================================================================
text:
  - platform: template
    name: "ED1 Matrix Text"
    id: matrix_text_input
    optimistic: true
    min_length: 0
    max_length: 20
    mode: text
