# ==============================================================================
# ED1 Core Package - Base configuration
# ==============================================================================
# Includes: ESP32 board, logger, API, OTA, WiFi, captive_portal
#
# Required substitutions:
#   - device_name: The ESPHome device name (e.g., ed1-kitchen)
#   - friendly_name: Human-readable name (e.g., ED1 Kitchen)
#   - ap_ssid: Fallback AP SSID (e.g., ED1-Kitchen-Rescue)
#
# Optional substitutions:
#   - wifi_power_save: WiFi power save mode (NONE, LIGHT, HIGH)
#                      Default: LIGHT (balanced for battery/USB)
#                      Use HIGH for battery-only, NONE for USB/wall power
# ==============================================================================

# Default substitution - can be overridden in device config
substitutions:
  wifi_power_save: "LIGHT"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  level: INFO

api:
  encryption:
    key: !secret api_encryption_key_full

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: ${wifi_power_save}
  fast_connect: true
  ap:
    ssid: ${ap_ssid}
    password: !secret fallback_ap_password

# Safe mode: auto-reboot on crash, fallback to OTA-only after repeated failures
safe_mode:
  boot_is_good_after: 60s
  num_attempts: 5

captive_portal:
