# ==============================================================================
# ED1 Sensors Package - Common sensors
# ==============================================================================

sensor:
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    id: wifi_signal_sensor
    update_interval: 10s

  - platform: uptime
    name: "${friendly_name} Uptime"
    id: uptime_sensor

  - platform: internal_temperature
    name: "${friendly_name} CPU Temperature"
    id: cpu_temp

  - platform: adc
    pin: GPIO34
    name: "${friendly_name} Light Level"
    id: light_sensor
    attenuation: 12db
    update_interval: 5s
    unit_of_measurement: "%"
    device_class: ""
    filters:
      - multiply: 30.3

text_sensor:
  - platform: wifi_info
    ssid:
      name: "${friendly_name} WiFi SSID"
      id: wifi_ssid
    ip_address:
      name: "${friendly_name} IP Address"
      id: wifi_ip
